### ISSUE TITLE
Desired animations

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-common#1]
I'm curious about a lot of the animations in the "Lab" screens (most notably for the shapes). Many of them seem really helpful, but others might not, so I'm curious to know whether each should be included. So far unimplemented yet:

1. Dragged circle slices rotate into position for the nearest "droppable" spot once picked up. This is implemented in Fractions: Intro, and I think it's very valuable (would like to keep it for sure).
2. Pulling circle/bar pieces from the toolbox has a "sizing up" animation (since the toolbox versions are smaller than the play-area versions). We've moved lately towards an "instantly bigger and dragging normally" thing that I prefer, so unless I hear otherwise, I'd probably have the pieces instantly jump up in size (and have their centroids under the mouse/touch so dragging looks better).
3. Returned pieces/etc. going to their spots in the "toolbox". Sounds really helpful, plan to implement.
4. "Undo" arrow fades in/out. We haven't been doing this in sims lately, so I would expect it is left out (but I'm fine implementing it, let me know)
5. Add/remove (+/-) buttons slide instead of going to their next location immediately. Then the next section (calling them "containers" internally but I'm up for whatever name) fades into place. Animates in the opposite form for removal. No preference, let me know whether it is desired ("may be valuable, but is a bit more complicated").
6. Haven't implemented the game, but when something is put in a collection box, it smoothly scales down into the correct place.
7. In the game, when one thing is complete and the play area is empty, another container animates to the center. I like this, will plan to do unless I hear otherwise.
8. Dropping pieces into containers also has an animation sliding into place. Similar to fractions-intro, it seems potentially valuable.

It would help to know which animations are desired before I work too much on refining any current code.

**Comment by jonathanolson** [comment]
https://www.colorado.edu/physics/phet/dev/html/fractions-mixed-numbers/1.0.0-dev.3/phet/fractions-mixed-numbers_en_phet.html?screens=3 is the current progress on the lab (shapes, basically no animations yet). Hopefully helps compare with/without.

**Comment by ariel-phet** [comment]
1. Dragged circle slices rotate into position for the nearest "droppable" spot once picked up. This is implemented in Fractions: Intro, and I think it's very valuable (would like to keep it for sure).
2. Pulling circle/bar pieces from the toolbox has a "sizing up" animation (since the toolbox versions are smaller than the play-area versions). We've moved lately towards an "instantly bigger and dragging normally" thing that I prefer, so unless I hear otherwise, I'd probably have the pieces instantly jump up in size (and have their centroids under the mouse/touch so dragging looks better).
3. Returned pieces/etc. going to their spots in the "toolbox". Sounds really helpful, plan to implement.
4. "Undo" arrow fades in/out. We haven't been doing this in sims lately, so I would expect it is left out (but I'm fine implementing it, let me know)
5. Add/remove (+/-) buttons slide instead of going to their next location immediately. Then the next section (calling them "containers" internally but I'm up for whatever name) fades into place. Animates in the opposite form for removal. No preference, let me know whether it is desired ("may be valuable, but is a bit more complicated").
6. Haven't implemented the game, but when something is put in a collection box, it smoothly scales down into the correct place.
7. In the game, when one thing is complete and the play area is empty, another container animates to the center. I like this, will plan to do unless I hear otherwise.
8. Dropping pieces into containers also has an animation sliding into place. Similar to fractions-intro, it seems potentially valuable.

**Comment by jonathanolson** [comment]
All of these were basically implemented. If we decide that (5) is needed, it will probably come up during testing/interviews/etc. Closing.
