### ISSUE TITLE
My Matches too cramped?

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/fractions-common#100]
For https://github.com/phetsims/QA/issues/294.

![issue](https://user-images.githubusercontent.com/31285590/53923577-05217080-4036-11e9-900d-7d048bb3d924.PNG)

Seen on Windows 10 + FF.

Looks bad to me.

**Comment by lmulhall-phet** [comment]
![issue2](https://user-images.githubusercontent.com/31285590/53924063-c1c80180-4037-11e9-93ea-e8ebdccecfa7.PNG)

**Comment by amanda-phet** [comment]
Seems related to https://github.com/phetsims/fractions-common/issues/86. 

@jonathanolson can you tweak the spacing some more for these extra wide challenges? Maybe the spacing between the equal sign and edges of the container should be the same, so they might be small but at least will be equally small?

**Comment by jonathanolson** [comment]
Also noticed that we don't have much room when both use the largest representation:

<img width="186" alt="Screen Shot 2019-04-02 at 10 52 47 AM" src="https://user-images.githubusercontent.com/480878/55421013-897fea00-5535-11e9-8dac-923e3930101e.png">

@ariel-phet or @amanda-phet, should any layout/sizing changes be made to compensate? This doesn't come up much naturally, but it did happen.

**Comment by jonathanolson** [comment]
Implemented. Also note that this puts the equals sign a bit off-center in common cases, e.g.:

<img width="176" alt="Screen Shot 2019-04-02 at 10 56 45 AM" src="https://user-images.githubusercontent.com/480878/55421304-2fcbef80-5536-11e9-9ed7-b14eae9780d2.png">
<img width="177" alt="Screen Shot 2019-04-02 at 10 56 58 AM" src="https://user-images.githubusercontent.com/480878/55421305-2fcbef80-5536-11e9-8d7b-d15b54889f76.png">

whereas before it was a bit more centered:

<img width="684" alt="screen shot 2019-02-21 at 11 23 24 am" src="https://user-images.githubusercontent.com/480878/53192287-53ad2480-35cb-11e9-9f5e-d2e722d804ca.png">

@amanda-phet and @ariel-phet, does this look good, and/or what should be done about the "difficult to fit" case noted in https://github.com/phetsims/fractions-common/issues/100#issuecomment-479092091?

**Comment by amanda-phet** [comment]
I don't mind the off-center equal sign since the matches are always listed horizontally. 

I am not sure what to do about that really cramped case... My only thought is to make them smaller.

**Comment by ariel-phet** [comment]
@jonathanolson I am also not bothered by the off center equal sign...

For the cramped case, I think making them smaller is fine. The point of the matches is to see that have you have completed them and have a reasonable idea of what they were. Having them be a bit small is acceptable since the matches are no longer central to the game play.

**Comment by jonathanolson** [comment]
I can adjust the scale so that it ensures whatever minimum level of padding.

The bare minimum to ensure nothing overlaps looks like:

<img width="159" alt="Screen Shot 2019-04-23 at 9 59 53 AM" src="https://user-images.githubusercontent.com/480878/56596938-b3658300-65ae-11e9-875e-10bd89df0f46.png">

But I also noticed that this happens in the bottom zone randomly sometimes:

<img width="311" alt="Screen Shot 2019-04-23 at 9 59 36 AM" src="https://user-images.githubusercontent.com/480878/56596963-c2e4cc00-65ae-11e9-88b0-5e314e706026.png">

So:

1. Should I bump up the minimum amount of padding in the targets so that there is more space in that type of constrained case?
2. Should anything be done about the overlap in the bottom?

**Comment by amanda-phet** [comment]
>Should I bump up the minimum amount of padding in the targets so that there is more space in that type of constrained case?

Thanks for finding this. Yes, we should slightly increase the padding. Even when there aren't two diamond shapes next to each other it looks strange.
![image](https://user-images.githubusercontent.com/7852916/56606768-3218eb00-65c4-11e9-92dc-22864238e367.png)

**Comment by jonathanolson** [comment]
Increased padding slightly now, so we have:

<img width="151" alt="Screen Shot 2019-04-23 at 2 06 52 PM" src="https://user-images.githubusercontent.com/480878/56612262-24b62d80-65d1-11e9-8667-167cf3ee385d.png">
<img width="150" alt="Screen Shot 2019-04-23 at 2 06 41 PM" src="https://user-images.githubusercontent.com/480878/56612274-297ae180-65d1-11e9-8468-98d520b8cec2.png">

Let me know if it needs further tweaks!

**Comment by amanda-phet** [comment]
Looks great. Thank you!
