### ISSUE TITLE
Pieces don't spread out

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#103]
For https://github.com/phetsims/QA/issues/294
I noticed some differences in what types of shapes show up in the dev est compared to the published version.  For one, the pieces don't spread out anymore like they do in the circled image below.  The boxes with a large number of partitions also don't seem to show up as much if at all.
![nomorespaces](https://user-images.githubusercontent.com/41024075/53986780-571cd180-40dc-11e9-8e49-91042998d1bb.jpg)

**Comment by jonathanolson** [comment]
When working with @ariel-phet, the order the shapes are filled in was changed to be more standard. Some partition shapes were limited.

However, I just noticed that I don't think the "random fill" levels are working properly, so I'm going to look into that.

**Comment by jonathanolson** [comment]
I believe horizontal/vertical bars are limited at 6 right now, and the plus signs / diagonal Ls were given minimums, which should be a change from the original sim's distribution.

I applied a fix above so that both the "mixed" fill type (left shape is full, right is random) and "random" fill type (both left and right are random) are used.

Thanks!
