### ISSUE TITLE
Generalize the undoArrowShape

### ISSUE THREAD

**Issue by Luisav1** [phetsims/fractions-common#116]
@chrisklus and I wanted a similar button to ReturnButton.js in Build a Nucleus to solve this issue https://github.com/phetsims/build-a-nucleus/issues/30. However the arrow shape is created inline. We think the shape can be generalized so we could use it to make a new button. But we're not sure where to put it or if the button should be generalized instead.

@jonathanolson could you make a recommendation for how we should proceed?

**Comment by jonathanolson** [comment]
Generalizing the shape sounds good, but also generalizing the button (if it will be used in multiple places) could be good also (some a11y/phet-io benefits potentially?)

**Comment by Luisav1** [comment]
Thanks @jonathanolson we went ahead and did those changes. @chrisklus and I moved the ReturnButton to scenery-phet, converted it to typescript, and tested it out in the sims it's used. Ready for review by @jonathanolson.

**Comment by marlitas** [comment]
Taking this review issue off of @jonathanolson's load.

Added some comments to the commits about naming. I addressed those in the above commit, otherwise the code looks good. 

I'm ready to close, but @Luisav1 and @chrisklus feel free to re-open if you have any questions or concerns about those changes.
