### ISSUE TITLE
Equality lab arrow/highlight behavior

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-common#17]
In the Java version there is an arrow and highlight on the right-side number line:

![fractions-equality-arrow](https://user-images.githubusercontent.com/480878/49206233-a41b3a00-f36e-11e8-8daf-70ac8be4960b.PNG)

The arrow seems to jump to the left for major ticks, and the highlight widens. I'm not sure I understand the height of the highlight, as it doesn't seem to cover any specific portion.

Should I match the Java version fairly precisely, or do something different? (Also the circle is semi-transparent, but isn't currently in HTML).

**Comment by ariel-phet** [comment]
@jonathanolson currently the behavior of the number line in the Equality Lab (in Java) matches the behavior of the number line representation in the Intro.

On the Intro tab, the highlighting makes sense, since you are always highlighting a particular tick mark on the number line.

However, for the Equality lab, I think it would be fine to remove the highlight (especially since we have the arrow). I see the point of the arrow, it is being very specific about a tick mark, since the number of tick mark divisions can be different on the right and left side. However, I also think it would be fine to maintain the same horizontal position of the arrow. So keep it as shown in the picture above, and when it reaches a major tick mark, simply overlay it on top of the major tick mark.

I would keep the circle semi-transparent.

**Comment by amanda-phet** [comment]
I'm fine with @ariel-phet 's suggestions. I think it would be fine to keep the highlight, but am not tied to it (because it has always bothered me that it is highlighting a range). However, the highlight exists in the Intro screens, and it seems like it would be more consistent to keep it.

**Comment by jonathanolson** [comment]
Implemented the desired improvements. Let's potentially look at the new appearance in design meeting?

**Comment by ariel-phet** [comment]
Looking pretty good to me, hopefully we are at a consensus at design :)

**Comment by amanda-phet** [comment]
12/6/18

Design meeting decision: make the major tick marks all the same weight (for some reason 0, 2, and 4 are thicker than 1 and 3). Keep the arrow a couple pixels to the left of the tick marks so it looks pointy.

**Comment by jonathanolson** [comment]
Should be changed, can you verify?

**Comment by amanda-phet** [comment]
It is looking good. I still prefer having the pink arrow jump to the left a little at the major tick marks so it looks pointy.

**Comment by jonathanolson** [comment]
Sorry about that, I'll get that implemented soon.

**Comment by jonathanolson** [comment]
Implemented.

Can you see if it looks good? I also enforced the previous somewhat-implicit choice that it's the left of the major tick marks that is aligned with the panel above (and not the arrow being aligned with the panel).

**Comment by amanda-phet** [comment]
All looks good to me!
