### ISSUE TITLE
Update Credits of Fractions sims

### ISSUE THREAD

**Issue by Denz1994** [phetsims/fractions-common#37]
Related to #29.

> Does a GitHub issue exist for tracking credits, to ensure that they are correct before publication?

All fractions-commmon related sims need their credits updated. I'm creating this issue to track this.

**Comment by jonathanolson** [comment]
@amanda-phet or @ariel-phet what should the credits be for the main 4 sims? Also do credits need to change for fraction-matcher at all?

**Comment by amanda-phet** [comment]
QA credits will need to be added for fraction-matcher but otherwise they can stay the same. (@KatieWoe should communicate QA credits for all sims after all testing is done.) 

**Fractions-Intro**
Ariel Paul (lead designer)
Jonathan Olson (developer) 
Sam Reid (original developer)
Mike Dubson
Trish Loeblein
Amanda McGarry
Kathy Perkins

**Fractions-Mixed-Numbers**
Amanda McGarry (lead designer)
Jonathan Olson (developer) 
Sam Reid (original developer)
Mike Dubson
Trish Loeblein
Ariel Paul
Kathy Perkins

**Fractions-Equality**
Ariel Paul (lead designer)
Jonathan Olson (developer) 
Sam Reid (original developer)
Mike Dubson
Trish Loeblein
Amanda McGarry
Kathy Perkins

**Build-a-Fraction**
Ariel Paul (lead designer)
Jonathan Olson (developer)
Sam Reid (original developer)
Mike Dubson
Karina K. R. Hensberry
Trish Loeblein
Amanda McGarry
Kathy Perkins

**Comment by ariel-phet** [comment]
@jonathanolson is also adding @veillette and some of his students where appropriate.

**Comment by jonathanolson** [comment]
Assigning to QA so this can be added before publication.

**Comment by KatieWoe** [comment]
QA for all add (if not there already): Steele, Laura, Jacob, Liam, Megan, Kelly, and myself

**Comment by jonathanolson** [comment]
QA credits fixes pushed, applied to release branches, and deployed.
