### ISSUE TITLE
Inconsistent layering of fraction objects

### ISSUE THREAD

**Issue by rea-laura** [phetsims/fractions-common#63]
<b>Test Device</b>

Leibniz

<b>Operating System</b>

iOS 12.1.1

<b>Browser</b>

Safari

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/251:

Layering of objects is inconsistent when they are dragged over other items or toolbars.

<b>Steps to Reproduce</b>

1) open sim
2) go to equality lab
3) select object from fraction bucket and drag over both left and right toolbars and fraction images. Note that the object appears over objects and toolbars on the left side of the equality, and under objects and toolbars on the right side of the equality.

<b>Visuals</b>

![layering](https://user-images.githubusercontent.com/44005544/50787754-8a75e800-1274-11e9-9190-44623584a2df.gif)

**Comment by jonathanolson** [comment]
Should be fixed with the above commit.

I also included changes so the draggable pieces consistently go in front of basically everything else (in the normal intro, mixed intro and equality-lab variants). @ariel-phet or @amanda-phet can you verify that the visual stacking order in these screens looks good?

**Comment by ariel-phet** [comment]
@jonathanolson that seems appropriate and looks good. I think having the draggable pieces go in front of everything matches expectations and works nicely since in general they animate back to a location so they cannot be left to cover up controls. Closing
