### ISSUE TITLE
Inconsistent bounds for different objects

### ISSUE THREAD

**Issue by rea-laura** [phetsims/fractions-common#69]
<b>Test Device</b>

Jordan

<b>Operating System</b>

macOS Mojave 10.14.2

<b>Browser</b>

Safari

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/250:

Bounds for different objects are inconsistent with each other. 

<b>Steps to Reproduce</b>

1) open sim
2) go to Build a Fraction
3) open any level
4) select and drag objects, noting the bounds. 
For levels where you build shapes, the shape template bounds are the sim itself and cannot be dragged beyond the back and reload buttons on the left or the fraction problems on the right. However, the pieces of the shapes can be dragged anywhere on the screen. 
The same thing happens for the levels where you build fractions. The fraction template is bounded by the sim, while the numbers to drag into the fraction can be dragged anywhere on the screen.

<b>Other details</b>

@ariel-phet @amanda-phet to determine which style to keep.

From Slack: 
Jonathan Olson [9:54 AM]
I definitely see what you mean. Would you mind creating an issue and asking Amanda/Ariel which style they would prefer? (I can limit the number movement, or unconstrain the shape movement, I don't have a preference). Thanks for finding that!

**Comment by rea-laura** [comment]
Found another case of inconsistent bounds in the "lab" section of the sim:
![kapture 2019-01-08 at 11 54 53](https://user-images.githubusercontent.com/44005544/50852463-d0967e80-133c-11e9-9209-82fa5a1249d6.gif)

**Comment by jonathanolson** [comment]
I'm actually starting to change my opinion, and may prefer to keep things as-is (or have a good reasoning for the changes) since:

1. I'm not a fan of restricting the dragging more than necessary in general.
2. It is impossible to drop a piece and have it "stay there" unless it's into a group. So if you drop something off screen, it flies back.
3. It looks like there is some interesting potential interaction between rotating shape pieces and how to adjust their "bounds" to stay inside the visible rectangle.

I want to make sure I have an explicit go-ahead to constrict the drag bounds for the pieces if desired, since it will be somewhat tricky for shape pieces.

**Comment by ariel-phet** [comment]
@rea-laura thanks for pointing out, but @jonathanolson makes a good point that even if dragged off screen nothing can get lost, and everything appears to be working.

Deciding to keep things as is, since it is working and not really doing any harm. Closing
