### ISSUE TITLE
Time of worse run recorded

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#92]
For https://github.com/phetsims/QA/issues/294
I'm not completely sure if this is a bug, but it is different from other games and it seems wrong to me.  If you beat a level quickly, but with wrong answers, the time is recorded on the level select page.  If you then beat the same level again with a slower time but all correct answers the time on the level select page is the faster time, though the stars show the better score.

**Comment by jonathanolson** [comment]
@amanda-phet when should a "best time" be recorded? I haven't really done that feature for games before.

**Comment by amanda-phet** [comment]
Aside: We REALLY need to have a sim design meeting about vegas. These game mechanics are all over the place and I can't keep track of it all. 

My understanding of times is that the time is only shown for a perfect score. I don't remember making a decision to post the time to the level selection screen for this sim, and it's not in the currently published sim. (But, why record time if it won't be posted?). 

Arithmetic doesn't show the time on the level selection screen, because you can always click the level and view your completed board + time. 

Graphing Lines only shows the time with a perfect score, and I recommend we do the same with Fraction Matcher.
![image](https://user-images.githubusercontent.com/7852916/53913357-689ca580-4018-11e9-8a39-718dddd5b75a.png)

**Comment by jonathanolson** [comment]
Only recording the score for perfect runs now.
